---
- name: Clean up the downloaded Neovim archive
  ansible.builtin.file:
    path: "{{ nvim_archive }}"
    state: absent
  listen: nvim_clean_download

- name: Clean up the temporary Neovim directory
  ansible.builtin.file:
    path: "{{ tmp_nvim_dir }}"
    state: absent
  listen: nvim_clean_tmp
# vi: ft=yaml.ansible
