---
- name: Install the login script
  ansible.builtin.copy:
    src: cloudauth
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: "0755"
    force: true

- name: Install the password generator script
  ansible.builtin.copy:
    src: pwgen
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: "0755"
    force: true

- name: Install the sessionizer
  ansible.builtin.copy:
    src: tmux-sessionizer
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: "0755"
    force: true

- name: Install the Terraform environment utility
  ansible.builtin.copy:
    src: tfenv
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: "0755"
    force: true
# vi: ft=yaml.ansible
