---
- name: Check if Cargo is installed
  ansible.builtin.command:
    cmd: cargo --version
  register: cargo_exists
  changed_when: false
  ignore_errors: true

- name: Install Rust
  when: cargo_exists is failed
  notify:
    - Clean up the temporary Rustup directory
  block:
    - name: Create a temporary directory for the Rustup script
      ansible.builtin.tempfile:
        state: directory
      register: tmp_rust

    - name: Set the temporary Rustup directory fact
      ansible.builtin.set_fact:
        tmp_rust_dir: "{{ tmp_rust.path }}"

    - name: Set the downloaded Rustup script fact
      ansible.builtin.set_fact:
        rustup: "{{ tmp_rust_dir }}/rustup-init.sh"

    - name: Ensure clean Rustup script download destination
      ansible.builtin.file:
        path: "{{ rustup }}"
        state: absent

    - name: Download the Rustup script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ rustup }}"
        mode: "0755"
        force: true
      notify:
        - Clean up the downloaded Rustup script

    - name: Install Rust and Cargo
      ansible.builtin.command:
        cmd: "{{ rustup }} --no-modify-path -y"
      changed_when: true
# vi: ft=yaml.ansible
