---
- name: Check if Cargo is installed
  ansible.builtin.command:
    cmd: "{{ ansible_user_dir }}/.cargo/bin/cargo --version"
  register: cargo_exists
  changed_when: false
  ignore_errors: true

- name: Install Rust
  when: cargo_exists is failed
  notify:
    - rust_clean_tmp
  block:
    - name: Create a temporary directory for the Rustup script
      ansible.builtin.tempfile:
        state: directory
      register: rust_tmp

    - name: Set the temporary Rustup directory fact
      ansible.builtin.set_fact:
        rust_tmp_dir: "{{ rust_tmp.path }}"

    - name: Set the downloaded Rustup script fact
      ansible.builtin.set_fact:
        rustup: "{{ rust_tmp_dir }}/rustup-init.sh"

    - name: Ensure clean Rustup script download destination
      ansible.builtin.file:
        path: "{{ rustup }}"
        state: absent

    - name: Download the Rustup script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ rustup }}"
        mode: "0755"
        force: true
      notify:
        - rust_clean_download

    - name: Install Rust and Cargo
      ansible.builtin.command:
        cmd: "{{ rustup }} --no-modify-path -y"
      changed_when: true

- name: Install Taplo
  community.general.homebrew:
    name:
      - taplo
    state: present
# vi: ft=yaml.ansible
