---
- name: Clean up the downloaded AWS CLI package
  ansible.builtin.file:
    path: "{{ aws_package }}"
    state: absent
  listen: aws_clean_download

- name: Clean up the temporary AWS CLI directory
  ansible.builtin.file:
    path: "{{ tmp_aws_dir }}"
    state: absent
  listen: aws_clean_tmp
# vi: ft=yaml.ansible
