---
- name: Install Lua tools
  community.general.homebrew:
    name:
      - luarocks
      - stylua
    state: present

- name: Install Luacheck
  ansible.builtin.command:
    cmd: "luarocks install luacheck"
  changed_when: true

- name: Install Selene
  community.general.cargo:
    name: selene
    state: present
# vi: ft=yaml.ansible
