---
- name: Clean up the downloaded Google Cloud CLI archive
  ansible.builtin.file:
    path: "{{ gcloud_archive }}"
    state: absent
  listen: gcloud_clean_download

- name: Clean up the temporary Google Cloud CLI directory
  ansible.builtin.file:
    path: "{{ gcloud_tmp_dir }}"
    state: absent
  listen: gcloud_clean_tmp
# vi: ft=yaml.ansible
