---
- name: Ensure the personal directory exists
  ansible.builtin.file:
    path: "{{ personal_dir }}"
    state: directory
    mode: "0755"

- name: Ensure the plugins directory exists
  ansible.builtin.file:
    path: "{{ plugins_dir }}"
    state: directory
    mode: "0755"

- name: Ensure the tools directory exists
  ansible.builtin.file:
    path: "{{ tools_dir }}"
    state: directory
    mode: "0755"

- name: Ensure the Visiosto directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/visiosto"
    state: directory
    mode: "0755"

- name: Ensure that the .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: Ensure that the .local directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local"
    state: directory
    mode: "0755"

- name: Ensure that the local binaries directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: "0755"
# vi: ft=yaml.ansible
