start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

[mode.main.binding]
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
# alt-enter = 'exec-and-forget open -n /Applications/kitty.app'
alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'

alt-h = 'focus left --boundaries-action wrap-around-the-workspace'
alt-j = 'focus down --boundaries-action wrap-around-the-workspace'
alt-k = 'focus up --boundaries-action wrap-around-the-workspace'
alt-l = 'focus right --boundaries-action wrap-around-the-workspace'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# alt-b = 'split horizontal' # originally as 'alt-h', but I prefer the Vim-like keybindings for windows
# alt-v = 'split vertical'
alt-b = 'join-with left'
alt-v = 'join-with down'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# The we just pretend that `mod1` is different for these actions.
ctrl-1 = 'workspace 1' # the main workspace
ctrl-2 = 'workspace 2' # the work workspace
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'

ctrl-shift-h = 'move-workspace-to-monitor --wrap-around prev'
ctrl-shift-l = 'move-workspace-to-monitor --wrap-around next'

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout tiling"]
