---
- name: Install virtual machine utilities
  community.general.homebrew:
    name:
      - roots/tap/trellis-cli
      - lima
      - hashicorp/tap/hashicorp-vagrant
    state: present
# vi: ft=yaml.ansible
