---
- name: Stat dotfiles development directory
  ansible.builtin.stat:
    path: "{{ dotfiles_dir }}"
  register: dotfiles

- name: Register the dotfiles development directory state fact
  ansible.builtin.set_fact:
    dotfiles_cloned: "{{ dotfiles.stat.exists }}"

- name: Debug the dotfiles development directory fact
  ansible.builtin.debug:
    var: dotfiles_cloned

- name: Clone anttikivi/dotfiles
  ansible.builtin.git:
    repo: git@github.com:anttikivi/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    version: main
    accept_newhostkey: true
  when: not dotfiles_cloned
# vi: ft=yaml.ansible
