default_roles:
  - alacritty
  - ansible
  # - aws
  - clang
  # - gcloud
  - go
  - lua
  - node
  - nvim
  - php
  - python
  - rust
  - sh
  - terraform
  - vm

config_dir: "{{ ansible_user_dir }}/.config"
xdg_config_home: "{{ config_dir }}"
env_dir: "{{ config_dir }}/env"

local_dir: "{{ ansible_user_dir }}/.local"
local_bin_dir: "{{ local_dir }}/bin"
local_lib_dir: "{{ local_dir }}/lib"
local_data_dir: "{{ local_dir }}/share"
local_state_dir: "{{ local_dir }}/state"
xdg_data_home: "{{ local_data_dir }}"
xdg_state_home: "{{ local_state_dir }}"
zsh_dir: "{{ ansible_user_dir }}/.zsh"

dev_dir: "{{ ansible_user_dir }}/development"
dotfiles_dir: "{{ dev_dir }}/dotfiles"
plugins_dir: "{{ dev_dir }}/plugins"
visiosto_dev_dir: "{{ dev_dir }}/visiosto"

implemented_color_schemes:
  catppuccin:
    name: catppuccin
    variants:
      dark:
        - frappe
        - macchiato
        - mocha
      light:
        - latte
  kanagawa:
    name: kanagawa
    colors:
      lotus_white_3: "#fdf7e4" # The background color
      lotus_white_4: "#e2d6be"
      lotus_white_5: "#e7dba0"
    variants:
      dark:
        - wave
        # - dragon
      light:
        - lotus
  rose_pine:
    name: rose-pine
    variants:
      dark:
        - main
        - moon
      light:
        - dawn

color_scheme:
  name: "{{ implemented_color_schemes.catppuccin.name }}"
  dark_variant: "{{ implemented_color_schemes.catppuccin.variants.dark[2] }}"
  light_variant: "{{ implemented_color_schemes.catppuccin.variants.light[0] }}"

git_user_name: Antti Kivi
git_user_email: "{{ vault_git_user_email }}"
git_signingkey: 501D24478EA632F0

# The Google Cloud CLI is not installed even if a newer version is available
# when `force` is set to `false`.
gcloud:
  version: 458.0.1
  force: false

# The AWS CLI is not installed even if a newer version is available
# when `force` is set to `false`.
aws:
  force: false

aws_login_session: "{{ vault_aws_login_session }}"
cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
gandi_personal_access_token: "{{ vault_gandi_personal_access_token }}"
gsap_npm_token: "{{ vault_gsap_npm_token }}"

ssh_keys:
  id_rsa: "{{ vault_id_rsa }}"
  id_rsa.pub: "{{ vault_id_rsa_pub }}"
  id_ed25519: "{{ vault_id_ed25519 }}"
  id_ed25519.pub: "{{ vault_id_ed25519_pub }}"

gpg_keys:
  signing: "{{ vault_gpg_signing }}"
  signing_pub: "{{ vault_gpg_signing_pub }}"
# vi: ft=yaml.ansible
