default_roles:
  - ansible
  - aws
  - clang
  - gcloud
  - go
  - kitty
  - lua
  - node
  - nvim
  - php
  - python
  - rust
  - sh
  - terraform
  - vm
  - zig

config_dir: "{{ ansible_user_dir }}/.config"
xdg_config_home: "{{ config_dir }}"
env_dir: "{{ config_dir }}/env"

local_dir: "{{ ansible_user_dir }}/.local"
local_bin_dir: "{{ local_dir }}/bin"
local_lib_dir: "{{ local_dir }}/lib"
local_data_dir: "{{ local_dir }}/share"
local_state_dir: "{{ local_dir }}/state"
local_opt_dir: "{{ local_dir }}/opt"
xdg_data_home: "{{ local_data_dir }}"
xdg_state_home: "{{ local_state_dir }}"

dev_dir: "{{ ansible_user_dir }}/development"
plugins_dev_dir: "{{ dev_dir }}/plugins"
learning_dev_dir: "{{ dev_dir }}/learning"
visiosto_dev_dir: "{{ dev_dir }}/visiosto"

etc_dir: "{{ ansible_user_dir }}/etc"
dotfiles_dir: "{{ etc_dir }}/dotfiles"

tmp_dir: "{{ ansible_user_dir }}/tmp"

uni_dir: "{{ ansible_user_dir }}/university"

zsh_dir: "{{ ansible_user_dir }}/.zsh"

implemented_color_schemes:
  catppuccin:
    name: catppuccin
    variants:
      dark:
        - frappe
        - macchiato
        - mocha
      light:
        - latte
  rose_pine:
    name: rose-pine
    variants:
      dark:
        - main
        - moon
      light:
        - dawn

color_scheme:
  name: "{{ implemented_color_schemes.catppuccin.name }}"
  dark_variant: "{{ implemented_color_schemes.catppuccin.variants.dark[2] }}"
  light_variant: "{{ implemented_color_schemes.catppuccin.variants.light[0] }}"

git_user_name: Antti Kivi
git_user_email: "{{ vault_git_user_email }}"
git_signingkey:
  "ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAILjvQuHORSaPmrzGaG6LX0nCqOvL4Mc4TkIRCeV4aAbc"
git_sign_program: /Applications/1Password.app/Contents/MacOS/op-ssh-sign

ssh_identity_agent:
  "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

aws_login_session: "{{ vault_aws_login_session }}"
cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
gandi_personal_access_token: "{{ vault_gandi_personal_access_token }}"
gsap_npm_token: "{{ vault_gsap_npm_token }}"
# vi: ft=yaml.ansible
