---
- name: Ensure that the .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0755"

- name: Copy SSH keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key.key }}"
    content: "{{ ssh_key.value }}"
    mode: "{{ ('.pub' in ssh_key.key) | ternary('0644', '0600') }}"
  no_log: true
  loop_control:
    loop_var: ssh_key
  with_dict: "{{ ssh_keys }}"

- name: Copy SSH configuration
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: "0644"
# vi: ft=yaml.ansible
