---
- name: Set the AWS CLI directory fact
  ansible.builtin.set_fact:
    aws_dir: "{{ local_opt_dir }}/aws-cli"

- name: Stat AWS CLI
  ansible.builtin.stat:
    path: "{{ aws_dir }}"
  register: aws_stat

- name: Install AWS CLI
  when: aws_force or not aws_stat.stat.exists
  notify:
    - aws_clean_tmp
  block:
    - name: Create a temporary directory for the AWS CLI package
      ansible.builtin.tempfile:
        state: directory
      register: aws_tmp

    - name: Set the temporary AWS CLI directory fact
      ansible.builtin.set_fact:
        aws_tmp_dir: "{{ aws_tmp.path }}"

    - name: Set the downloaded AWS CLI package fact
      ansible.builtin.set_fact:
        aws_package: "{{ aws_tmp_dir }}/AWSCLIV2.pkg"

    - name: Ensure clean AWS CLI package download destination
      ansible.builtin.file:
        path: "{{ aws_package }}"
        state: absent

    - name: Download the AWS CLI package
      ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/AWSCLIV2.pkg"
        dest: "{{ aws_package }}"
        mode: "0644"
        force: true
      notify:
        - aws_clean_download

    - name: Ensure clean AWS CLI installation destination
      ansible.builtin.file:
        path: "{{ aws_dir }}"
        state: absent

    - name: Copy the installer choices file
      ansible.builtin.template:
        src: choices.xml.j2
        dest: "{{ local_data_dir }}/aws_choices.xml"
        mode: "0644"
        force: true

    - name: Install the AWS CLI
      ansible.builtin.command:
        cmd:
          "installer -pkg {{ aws_package }} -target CurrentUserHomeDirectory
          -applyChoiceChangesXML {{ local_data_dir }}/aws_choices.xml"
        creates:
          - "{{ aws_dir }}/aws"
          - "{{ aws_dir }}/aws_completer"
      changed_when: true
      register: aws_install_sh
      failed_when: aws_install_sh.rc != 0

    - name: Remove old link to the `aws` executable
      ansible.builtin.file:
        path: "{{ local_bin_dir }}/aws"
        state: absent

    - name: Create link to the `aws` executable
      ansible.builtin.file:
        path: "{{ local_bin_dir }}/aws"
        src: "{{ aws_dir }}/aws"
        state: link
        mode: "0755"

    - name: Remove old link to the `aws_completer` executable
      ansible.builtin.file:
        path: "{{ local_bin_dir }}/aws_completer"
        state: absent

    - name: Create link to the `aws_completer` executable
      ansible.builtin.file:
        path: "{{ local_bin_dir }}/aws_completer"
        src: "{{ aws_dir }}/aws_completer"
        state: link
        mode: "0755"
# vi: ft=yaml.ansible
