---
- name: Install GNU utilities
  community.general.homebrew:
    name:
      - gnu-tar
      - stow
    state: present

- name: Install general utilities
  community.general.homebrew:
    name:
      - fzf
      - ripgrep
    state: present
# vi: ft=yaml.ansible
