---
- name: Install general utilities
  community.general.homebrew:
    name:
      - catimg
      - fzf
      - gnu-tar
      - jq
      - ripgrep
      - scdoc
      - tree
    state: present

- name: Install AeroSpace
  when: utils_install_aerospace | bool
  block:
    - name: Link the AeroSpace configuration
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/config/aerospace.toml"
        dest: "{{ ansible_user_dir }}/.aerospace.toml"
        state: link
        force: true

    - name: Tap the repository for AeroSpace
      community.general.homebrew_tap:
        name: nikitabobko/tap
        state: present

    - name: Install AeroSpace
      community.general.homebrew_cask:
        name:
          - nikitabobko/tap/aerospace
        state: present

- name: Install skhd
  when: utils_install_skhd | bool
  block:
    - name: Link the skhd configuration
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/config/skhdrc"
        dest: "{{ ansible_user_dir }}/.skhdrc"
        state: link
        force: true

    - name: Tap the repository for skhd
      community.general.homebrew_tap:
        name: koekeishiya/formulae
        state: present

    - name: Install skhd
      community.general.homebrew:
        name:
          - koekeishiya/formulae/skhd
        state: present

- name: Install yabai
  when: utils_install_yabai | bool
  block:
    - name: Link the yabai configuration
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/config/yabairc"
        dest: "{{ ansible_user_dir }}/.yabairc"
        state: link
        force: true

    - name: Tap the repository for yabai
      community.general.homebrew_tap:
        name: koekeishiya/formulae
        state: present

    - name: Install yabai
      community.general.homebrew:
        name:
          - koekeishiya/formulae/yabai
        state: present

- name: Link the global `.editorconfig`
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/editorconfig"
    dest: "{{ ansible_user_dir }}/.editorconfig"
    state: link
    force: true
# vi: ft=yaml.ansible
