---
- name: Install GNU utilities
  community.general.homebrew:
    name:
      - gnu-tar
      - stow
    state: present

- name: Install general utilities
  community.general.homebrew:
    name:
      - fzf
      - ripgrep
    state: present

- name: Tap the repository for skhd
  community.general.homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: Install skhd
  community.general.homebrew:
    name:
      - koekeishiya/formulae/skhd
    state: present

- name: Install Hugo
  community.general.homebrew:
    name:
      - hugo
    state: present
# vi: ft=yaml.ansible
