---
- name: Install GNU utilities
  community.general.homebrew:
    name:
      - gnu-tar
      - stow
    state: present

- name: Install general utilities
  community.general.homebrew:
    name:
      - fzf
      - ripgrep
    state: present

- name: Link the skhd configuration
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/skhdrc"
    dest: "{{ ansible_user_dir }}/.skhdrc"
    state: link
    force: true

- name: Tap the repository for skhd
  community.general.homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: Install skhd
  community.general.homebrew:
    name:
      - koekeishiya/formulae/skhd
    state: present

- name: Link the global `.editorconfig`
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/editorconfig"
    dest: "{{ ansible_user_dir }}/.editorconfig"
    state: link
    force: true
# vi: ft=yaml.ansible
