start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# alt-b = 'split horizontal' # originally as 'alt-h', but I prefer the Vim-like keybindings for windows
# alt-v = 'split vertical'
alt-b = 'join-with left'
alt-v = 'join-with down'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# The we just pretend that `mod1` is different for these actions.
cmd-1 = 'workspace 1' # the main workspace
cmd-2 = 'workspace 2' # the work workspace

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-shift-c = 'reload-config'

# alt-shift-w = 'mode workspaces'
alt-r = 'mode resize'

# Not quite i3, but the default keybinding conflict with important keys on
# Finnish keyboard.
# [mode.workspaces.binding]
# alt-1 = 'workspace 1'                    # the main workspace
# alt-w = 'workspace w'                    # the work workspace
# alt-shift-1 = 'move-node-to-workspace 1'
# alt-shift-w = 'move-node-to-workspace w'
# enter = 'mode main'
# esc = 'mode main'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
