import = ["~/.config/alacritty/colors.toml"]

live_config_reload = true
ipc_socket = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 1, y = 1 }
dynamic_padding = false
dynamic_title = true
decorations = "Full"
decorations_theme_variant = "None"
resize_increments = false
# TODO: Make sure the option key works as intended
# option_as_alt = "None"

[scrolling]
history = 8192 # Max value is 100000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.5
