import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true
ipc_socket = true

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false
# TODO: Make sure the option key works as intended
# option_as_alt = "None"

[scrolling]
history = 1000 # Max value is 100000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.25
