---
- name: Run Darwin tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install modules
  ansible.builtin.import_tasks: modules.yml

- name: Install modules with Darwin-specific tasks
  ansible.builtin.import_tasks: darwin_modules.yml
  when: ansible_os_family == 'Darwin'
# vi: ft=yaml.ansible
