---
- name: Install Go modules
  ansible.builtin.command:
    cmd: "go install {{ item.module }}"
    creates: "{{ go_gopath }}/bin/{{ item.cmd }}"
  environment:
    GOPATH: "{{ go_gopath }}"
  register: go_install
  changed_when: go_install.rc != 0
  loop_control:
    label: "{{ item.module }}"
  loop: "{{ go_modules }}"
  when: go_modules is defined
# vi: ft=yaml.ansible
