---
- name: Install Go modules
  ansible.builtin.command:
    cmd: "go install {{ item.module }}"
    creates: "{{ ansible_user_dir }}/go/bin/{{ item.cmd }}"
  register: go_install
  changed_when: go_install.rc != 0
  loop_control:
    label: "{{ item.module }}"
  loop: "{{ go.modules }}"
  when: go.modules is defined
# vi: ft=yaml.ansible
