---
- name: Install Go modules
  ansible.builtin.command:
    cmd: "go install {{ item.module }}"
    creates: "{{ ansible_user_dir }}/go/bin/{{ item.cmd }}"
  register: go_install
  changed_when: go_install.rc != 0
  loop_control:
    label: "{{ item.module }}"
  loop: "{{ go.modules }}"
  when: go.modules is defined

- name: Install Hugo
  block:
    - name: Install Hugo
      ansible.builtin.command:
        cmd: "go install -tags extended github.com/gohugoio/hugo@v0.123.8"
        creates: "{{ ansible_user_dir }}/go/bin/hugo"
      environment:
        CGO_ENABLED: "1"
        GOPATH: "{{ ansible_user_dir }}/go"
      register: hugo_install
      changed_when: hugo_install.rc != 0
# vi: ft=yaml.ansible
