---
- name: Tap the HashiCorp repository
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install Terraform
  community.general.homebrew:
    name: hashicorp/tap/terraform
    state: present
# vi: ft=yaml.ansible
