---
- name: Tap the HashiCorp repository
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install Terraform
  community.general.homebrew:
    name: hashicorp/tap/terraform
    state: present

- name: Create the Terraform variables file
  ansible.builtin.template:
    src: terraform.tfvars.j2
    dest: "{{ dotfiles_dir }}/terraform.tfvars"
    mode: "0644"
    force: true
# vi: ft=yaml.ansible
