---
- name: Tap the repository for yabai
  community.general.homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: Install yabai
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
    state: present

- name: Link the yabai configuration
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/yabairc"
    dest: "{{ ansible_user_dir }}/.yabairc"
    state: link
    force: true
# vi: ft=yaml.ansible
