---
- name: Clean up the downloaded Rustup script
  ansible.builtin.file:
    path: "{{ rustup }}"
    state: absent
  listen: rust_clean_download

- name: Clean up the temporary Rustup directory
  ansible.builtin.file:
    path: "{{ rust_tmp_dir }}"
    state: absent
  listen: rust_clean_tmp
# vi: ft=yaml.ansible
