---
- name: Install Tmux and its dependencies
  community.general.homebrew:
    name:
      - tmux
      - reattach-to-user-namespace
    state: present

- name: Link the Tmux configuration
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link
    force: true
# vi: ft=yaml.ansible
