---
- name: Ensure that the nvm directory exists
  ansible.builtin.file:
    path: "{{ node_nvm_dir }}"
    state: directory
    mode: "0755"

- name: Copy the configuration for default global packages
  ansible.builtin.copy:
    src: default-packages
    dest: "{{ node_nvm_dir }}/default-packages"
    mode: "0644"
    force: true

- name: Get the nvm version
  ansible.builtin.shell:
    cmd: |
      source {{ node_nvm_dir }}/nvm.sh
      nvm --version --no-colors
  register: nvm_current_version_sh
  changed_when: false
  failed_when: false

- name: Set the current nvm version fact
  ansible.builtin.set_fact:
    nvm_current_version: "v{{ nvm_current_version_sh.stdout | default('') }}"

- name: Query the latest nvm version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo $(curl -LsS https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r '.tag_name')
  register: nvm_latest_version_sh
  changed_when: false

- name: Set the latest nvm version fact
  ansible.builtin.set_fact:
    nvm_latest_version: "{{ nvm_latest_version_sh.stdout | default('') }}"

- name: Install nvm
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_latest_version }}/install.sh | bash
  environment:
    NVM_DIR: "{{ node_nvm_dir }}"
    PROFILE: /dev/null
  args:
    creates: "{{ node_nvm_dir }}/nvm.sh"
  when: nvm_latest_version not in nvm_current_version
  changed_when: nvm_latest_version not in nvm_current_version

- name: Install Node.js
  ansible.builtin.include_tasks: darwin_install_node.yml
  loop: "{{ node_versions }}"

- name: Set the default Node.js version
  ansible.builtin.shell:
    cmd: |
      source {{ node_nvm_dir }}/nvm.sh
      nvm alias default {{ node_default_version }} --no-colors
  changed_when: true
  environment:
    NVM_DIR: "{{ node_nvm_dir }}"
# vi: ft=yaml.ansible
