---
- name: Debug the required Alacritty version
  ansible.builtin.debug:
    var: alacritty.version

- name: Resolve the required Alacritty minor version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo "{{ alacritty.version }}" | head -c $(echo "{{ alacritty.version }}" | grep -m 2 -ob "\." | tail -1 | grep -oE "[0-9]+")
  register: required_alacritty_minor_sh
  changed_when: false
  failed_when: false

- name: Set the required Alacritty minor version fact
  ansible.builtin.set_fact:
    required_alacritty_minor_version:
      "{{ required_alacritty_minor_sh.stdout | default('') }}"

- name: Debug the required Alacritty minor version fact
  ansible.builtin.debug:
    var: required_alacritty_minor_version

- name: Resolve the wanted Alacritty version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -LsS https://api.github.com/repos/alacritty/alacritty/releases?per_page=30 | jq -r '.[] | .tag_name' | grep "{{ required_alacritty_minor_version | replace('.', '\\.') }}" | grep "\\-rc" | sort -V | tail -1
  register: wanted_alacritty_version_sh
  changed_when: false
  failed_when: wanted_alacritty_version_sh.rc != 0

- name: Set the wanted Alacritty version fact
  ansible.builtin.set_fact:
    wanted_alacritty_version:
      "{{ wanted_alacritty_version_sh.stdout | default('') }}"

- name: Debug the wanted Alacritty version fact
  ansible.builtin.debug:
    var: wanted_alacritty_version

- name: Get the Alacritty version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      # TODO: The lengths shouldn't be hard-coded.
      alacritty --version | head --lines 1 | cut -c 11-17
  register: current_alacritty_version_sh
  changed_when: false
  failed_when: false

- name: Set the current Alacritty version fact
  ansible.builtin.set_fact:
    current_alacritty_version:
      "v{{ current_alacritty_version_sh.stdout | default('') }}"

- name: Debug the current Alacritty version
  ansible.builtin.debug:
    var: current_alacritty_version

- name: Install Alacritty
  when: wanted_alacritty_version != current_alacritty_version
  notify:
    - Clean up the temporary Alacritty directory
  block:
    - name: Create a temporary directory for Alacritty
      ansible.builtin.tempfile:
        state: directory
      register: tmp_alacritty

    - name: Set the temporary Alacritty directory fact
      ansible.builtin.set_fact:
        tmp_alacritty_dir: "{{ tmp_alacritty.path }}"

    - name: Set the cloned Alacritty directory fact
      ansible.builtin.set_fact:
        alacritty_dir: "{{ tmp_alacritty_dir }}/alacritty"

    - name: Clone Alacritty
      ansible.builtin.git:
        dest: "{{ alacritty_dir }}"
        repo: https://github.com/alacritty/alacritty.git
        depth: 1
        version: "{{ wanted_alacritty_version }}"

    - name: Build Alacritty
      community.general.make:
        chdir: "{{ alacritty_dir }}"
        target: app

    - name: Copy Alacritty.app to Applications
      ansible.builtin.copy:
        src: "{{ alacritty_dir }}/target/release/osx/Alacritty.app"
        dest: /Applications
        mode: preserve

    - name: Set up Alacritty's `terminfo`
      ansible.builtin.command:
        cmd: tic -xe alacritty,alacritty-direct extra/alacritty.info
        chdir: "{{ alacritty_dir }}"
      changed_when: true

    - name: Ensure that the `man1` directory exists
      ansible.builtint.file:
        path: /usr/local/share/man/man1
        state: directory
        mode: "755"

    - name: Ensure that the `man5` directory exists
      ansible.builtint.file:
        path: /usr/local/share/man/man5
        state: directory
        mode: "755"

    - name: Set up Alacritty's manual page
      ansible.builtin.command:
        cmd: |
          scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
          scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
          scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
          scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
        chdir: "{{ alacritty_dir }}"
      changed_when: true

    - name: Ensure that the `.zsh_completion` directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zsh_completion"
        state: directory
        mode: "755"

    - name: Copy the Alacritty completions
      ansible.builtin.copy:
        src: "{{ alacritty_dir }}/extra/completions/_alacritty"
        dest: "{{ ansible_user_dir }}/.zsh_completion/_alacritty"
        mode: "644"

- name: Ensure that the Alacritty configuration directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    mode: "755"

- name: Link the Alacritty configuration
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/config/alacritty.toml"
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.toml"
    state: link
    force: true
# vi: ft=yaml.ansible
