require("dot.config.options")
require("dot.config.autocmds")
require("dot.config.keymaps")

require("dot.pack").setup()
require("dot.root").setup()
require("dot.languages").setup()
require("dot.cmp").setup()
require("dot.mason").setup()
require("dot.lsp").setup()
require("dot.lint").setup()
require("dot.treesitter").setup()
require("dot.explorer").setup()
require("dot.harpoon").setup()
require("dot.colors").setup()
