require("dot.config.options")
require("dot.config.keymaps")

require("dot.pack").setup()
require("dot.languages").setup()
require("dot.mason").setup()
require("dot.lsp").setup()
require("dot.explorer").setup()
require("dot.harpoon").setup()
require("dot.colors").setup()
