---
- name: Set the kitty installation directory fact
  ansible.builtin.set_fact:
    kitty_bin_dir: /Applications/kitty.app/Contents/MacOS
    kitty_creates_dir: /Applications/kitty.app

- name: Debug the required kitty version
  ansible.builtin.debug:
    var: common_kitty_version

- name: Resolve the required kitty minor version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo "{{ common_kitty_version }}" | head -c $(echo "{{ common_kitty_version }}" | grep -m 2 -ob "\." | tail -1 | grep -oE "[0-9]+")
  register: kitty_required_minor_sh
  changed_when: false
  failed_when: false

- name: Set the required kitty minor version fact
  ansible.builtin.set_fact:
    kitty_required_minor_version:
      "{{ kitty_required_minor_sh.stdout | default('') }}"

- name: Debug the required kitty minor version fact
  ansible.builtin.debug:
    var: kitty_required_minor_version

- name: Resolve the wanted kitty version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -LsS -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/kovidgoyal/kitty/releases | jq -r '.[] | .tag_name' | grep "{{ kitty_required_minor_version | replace('.', '\\.') }}" | sort -V | tail -1
  register: kitty_wanted_version_sh
  changed_when: false
  failed_when: kitty_wanted_version_sh.rc != 0

- name: Set the wanted kitty version fact
  ansible.builtin.set_fact:
    kitty_wanted_version: "{{ kitty_wanted_version_sh.stdout | default('') }}"

- name: Debug the wanted kitty version fact
  ansible.builtin.debug:
    var: kitty_wanted_version

- name: Get the kitty version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      {{ kitty_bin_dir }}/kitty --version | cut -c $(($({{ kitty_bin_dir }}/kitty --version | grep -ob "\ " | head -1 | grep -oE "[0-9]+") + 2))-$({{ kitty_bin_dir }}/kitty --version | grep -ob "\ " | head -2 | tail -1 | grep -oE "[0-9]+")
  register: kitty_current_version_sh
  changed_when: false
  failed_when: kitty_current_version_sh.rc != 0

- name: Set the current kitty version fact
  ansible.builtin.set_fact:
    kitty_current_version:
      "v{{ kitty_current_version_sh.stdout | default('') }}"

- name: Debug the current kitty version fact
  ansible.builtin.debug:
    var: kitty_current_version

- name: Remove the old kitty installation
  ansible.builtin.file:
    path: "{{ kitty_creates_dir }}"
    state: absent
  when: kitty_wanted_version != kitty_current_version

- name: Install kitty
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
    creates: "{{ kitty_creates_dir }}"
# vi: ft=yaml.ansible
