---
- name: Load the variables
  ansible.builtin.include_vars: "{{ item.value }}"
  when: ansible_os_family == item.key
  with_items:
    - { key: "Darwin", value: "vars/darwin.yml" }

- name: Include the SSH variables
  ansible.builtin.include_vars: ssh.yml

- name: Include the secret variables
  ansible.builtin.include_vars: secret.yml

- name: Run Darwin tasks
  when: ansible_os_family == 'Darwin'
  block:
    - name: Run the basic SSH tasks
      ansible.builtin.import_tasks: darwin_ssh.yml

    - name: Run the secret SSH tasks
      ansible.builtin.import_tasks: darwin_secret_ssh.yml

    - name: Run the tasks
      ansible.builtin.import_tasks: darwin.yml

    - name: Run the secret tasks
      ansible.builtin.import_tasks: darwin_secret.yml

    - name: Run the Neovim tasks
      ansible.builtin.import_tasks: darwin_nvim.yml
# vi: ft=yaml.ansible
