---
- name: Get the Tailwind version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      tailwindcss --help | head --lines 2 | tail --lines 1 | sed 's/tailwindcss //'
  register: current_tailwind_version_sh
  changed_when: false
  failed_when: false

- name: Set the current Tailwind version fact
  ansible.builtin.set_fact:
    current_tailwind_version:
      "{{ current_tailwind_version_sh.stdout | default('') }}"

- name: Query the latest Tailwind version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -LsS https://api.github.com/repos/tailwindlabs/tailwindcss/releases/latest | jq '.tag_name' | tr -d '"'
  register: latest_tailwind_version_sh
  changed_when: false

- name: Set the latest Tailwind version fact
  ansible.builtin.set_fact:
    latest_tailwind_version:
      "{{ latest_tailwind_version_sh.stdout | default('') }}"

- name: Debug the current Tailwind version
  ansible.builtin.debug:
    var: current_tailwind_version

- name: Debug the latest Tailwind version
  ansible.builtin.debug:
    var: latest_tailwind_version

- name: Install Tailwind
  when: latest_tailwind_version not in current_tailwind_version
  block:
    - name: Set the Tailwind directory fact
      ansible.builtin.set_fact:
        tailwind_dir: "{{ tools_dir }}/tailwindcss"

    - name: Create a directory for Tailwind
      ansible.builtin.file:
        path: "{{ tailwind_dir }}"
        state: directory
        mode: "0755"

    - name: Set the Tailwind executable fact
      ansible.builtin.set_fact:
        tailwind_exe: "{{ tailwind_dir }}/tailwindcss"

    - name: Ensure clean Tailwind executable destination
      ansible.builtin.file:
        path: "{{ tailwind_exe }}"
        state: absent

    - name: Download Tailwind
      ansible.builtin.get_url:
        url: "https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64"
        dest: "{{ tailwind_exe }}"
        mode: "0755"
        force: true
# vi: ft=yaml.ansible
