---
- name: Debug the required Neovim version
  ansible.builtin.debug:
    var: nvim.version

- name: Resolve the required Neovim minor version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo "{{ nvim.version }}" | head -c $(echo "{{ nvim.version }}" | grep -m 2 -ob "\." | tail -1 | grep -oE "[0-9]+")
  register: required_nvim_minor_sh
  changed_when: false
  failed_when: false

- name: Set the required Neovim minor version fact
  ansible.builtin.set_fact:
    required_nvim_minor_version:
      "{{ required_nvim_minor_sh.stdout | default('') }}"

- name: Debug the required Neovim minor version fact
  ansible.builtin.debug:
    var: required_nvim_minor_version

- name: Resolve the wanted Neovim version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -LsS https://api.github.com/repos/neovim/neovim/releases?per_page=30 | jq -r '.[] | .tag_name' | grep "{{ required_nvim_minor_version | replace('.', '\\.') }}" | sort -V | tail -1
  register: wanted_nvim_version_sh
  changed_when: false
  failed_when: wanted_nvim_version_sh.rc != 0

- name: Set the wanted Neovim version fact
  ansible.builtin.set_fact:
    wanted_nvim_version: "{{ wanted_nvim_version_sh.stdout | default('') }}"

- name: Debug the wanted Neovim version fact
  ansible.builtin.debug:
    var: wanted_nvim_version

- name: Get the Neovim version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      nvim --version | head --lines 1 | cut -c 6-
  register: current_nvim_version_sh
  changed_when: false
  failed_when: false

- name: Set the current Neovim version fact
  ansible.builtin.set_fact:
    current_nvim_version: "{{ current_nvim_version_sh.stdout | default('') }}"

- name: Debug the current Neovim version
  ansible.builtin.debug:
    var: current_nvim_version

- name: Install Neovim
  when: wanted_nvim_version != current_nvim_version
  notify:
    - Clean up the temporary Neovim directory
  block:
    - name: Set the Neovim archive name fact
      ansible.builtin.set_fact:
        # TODO: This apparently needs to be changed for Neovim v0.10.
        nvim_archive_name: nvim-macos-arm64

    - name: Set the Neovim archive filename fact
      ansible.builtin.set_fact:
        nvim_archive_filename: "{{ nvim_archive_name }}.tar.gz"

    - name: Create a temporary directory for the Neovim archive
      ansible.builtin.tempfile:
        state: directory
      register: tmp_nvim

    - name: Set the temporary Neovim directory fact
      ansible.builtin.set_fact:
        tmp_nvim_dir: "{{ tmp_nvim.path }}"

    - name: Set the downloaded Neovim archive fact
      ansible.builtin.set_fact:
        nvim_archive: "{{ tmp_nvim_dir }}/{{ nvim_archive_filename }}"

    - name: Ensure clean Neovim archive download destination
      ansible.builtin.file:
        path: "{{ nvim_archive }}"
        state: absent

    - name: Resolve the Neovim download URL
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -LsS https://api.github.com/repos/neovim/neovim/releases/tags/{{ wanted_nvim_version }} | jq -r '.assets.[] | select(.name | endswith("{{ nvim_archive_filename }}")) | .browser_download_url'
      register: nvim_url_sh
      changed_when: false
      failed_when: nvim_url_sh.rc != 0

    - name: Set the Neovim download URL fact
      ansible.builtin.set_fact:
        nvim_url: "{{ nvim_url_sh.stdout | default('') }}"

    - name: Download the Neovim archive
      ansible.builtin.get_url:
        url: "{{ nvim_url }}"
        dest: "{{ nvim_archive }}"
        mode: "0644"
        force: true
      notify:
        - Clean up the downloaded Neovim archive

    - name: Remove existing Neovim installation
      ansible.builtin.file:
        path: "{{ tools_dir }}/nvim"
        state: absent

    - name: Ensure that the tools directory exists
      ansible.builtin.file:
        path: "{{ tools_dir }}"
        state: directory
        mode: "0755"

    - name: Extract and install Neovim
      ansible.builtin.unarchive:
        src: "{{ nvim_archive }}"
        dest: "{{ tools_dir }}"

    - name: Move the Neovim directory to the correct destination
      ansible.builtin.command:
        cmd: "mv {{ tools_dir }}/{{ nvim_archive_name }} {{ tools_dir }}/nvim"
      changed_when: true
# vi: ft=yaml.ansible
