---
- name: Tap the repository for dark-notify
  community.general.homebrew_tap:
    name: cormacrelf/tap
    state: present

- name: Install dark-notify
  community.general.homebrew:
    name:
      - cormacrelf/tap/dark-notify
    state: present

- name: Stat Brunch
  ansible.builtin.stat:
    path: "{{ plugins_dir }}/brunch.nvim"
  register: brunch

- name: Register Brunch state fact
  ansible.builtin.set_fact:
    brunch_installed: "{{ brunch.stat.exists }}"

- name: Debug the Brunch fact
  ansible.builtin.debug:
    var: brunch_installed

- name: Clone anttikivi/brunch.nvim
  ansible.builtin.git:
    repo: git@github.com:anttikivi/brunch.nvim.git
    dest: "{{ plugins_dir }}/brunch.nvim"
    version: main
    accept_newhostkey: true
  when: not brunch_installed

- name: Link the Neovim configuration
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
# vi: ft=yaml.ansible
