---
- name: Load the variables
  ansible.builtin.include_vars: "{{ item.value }}"
  when: ansible_os_family == item.key
  with_items:
    - { key: "Darwin", value: "vars/darwin.yml" }

- name: Run Darwin tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
# vi: ft=yaml.ansible
