name: Main workflow

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if:
      "!contains(github.event.head_commit.message, '[ci skip]') &&
      !startsWith(github.event.head_commit.message, 'docs')"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Install Python packages
        run: pip install ansible-lint

      - name: Install Cargo dependencies
        run: cargo install stylua selene

      - name: Cache the Cargo dependencies
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Install Go modules
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Install LuaRocks
        run: sudo apt install luarocks

      - name: Install Lua tools
        run: luarocks install luacheck --local

      - name: Install ShellCheck
        run: sudo apt install shellcheck

      - name: Lint the workspaces
        run: make lint
